### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by liweiGe** [getActivity/ToastUtils#30]
View android.widget.TextView{81a4017 V.ED..... ......ID 0,0-0,0 #102000b android:id/message} has already been added to the window manager.

android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:335)

线上还是报这异常,这是toast通病,不知道有解决办法没有

**Comment by getActivity** [comment]
库版本是否是最新的？还有Bug复现步骤说一下

**Comment by liweiGe** [comment]
库是最新的，线上bugly反馈的，这个百度了还是很多的

**Comment by getActivity** [comment]
@UserName-Haha ToastUtils的show方法是经过特殊处理，会将show任务收到队列中去，只有等上一个Toast消失才会显示下一个，并且我这边也测试了你刚刚说的那种情况，并不会出现报错，那种情况很可能是你们使用了系统原生的Toast导致的，要检查项目中报错的位置是否为ToastUtils类报的错

**Comment by UserName-Haha** [comment]
这个是错误信息，应该是Toast的TextView被多次添加到WindowMangerService里导致的
 java.lang.IllegalStateException: View android.widget.TextView{f2085ce V.ED..... ......ID 0,0-528,117 #7f0a0042 app:id/toast_main_text_view_id} has already been added to the window manager.
                                                                           at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:345)
                                                                           at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:129)
                                                                           at android.widget.Toast$TN.handleShow(Toast.java:501)
                                                                           at android.widget.Toast$TN$1.handleMessage(Toast.java:403)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:109)
                                                                           at android.os.Looper.loop(Looper.java:207)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7470)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by getActivity** [comment]
toast_main_text_view_id这个id在5.2的版本就已经移除了，请你先升级到最新的版本库再进行测试

**Comment by UserName-Haha** [comment]
> toast_main_text_view_id这个ID在5.2的版本就已经移除了，请你先升级到最新的版本库再进行测试

项目拉到本地依赖的，没及时更新，升级新版后已解决，感谢群主！！！
