### ISSUE TITLE
Android 9.0 华为机型

### ISSUE THREAD

**Issue by yizuochengchi** [getActivity/ToastUtils#41]
关掉通知栏权限后友盟报错

java.lang.IllegalStateException: View android.widget.TextView{93b6bee V.ED..... ......ID 0,0-0,0 #102000b android:id/message} has already been added to the window manager.
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:371)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:131)
	at android.widget.Toast$TN.handleShow(Toast.java:501)
	at android.widget.Toast$TN$1.handleMessage(Toast.java:403)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

能重现 不会崩溃但是吐司不提示 望fix 多谢！

**Comment by yizuochengchi** [comment]
已处理 多谢解答
