### ISSUE TITLE
报一下错误

### ISSUE THREAD

**Issue by csh159** [getActivity/ToastUtils#49]
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7905)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1276)
	at android.view.View.requestLayout(View.java:22139)
	at android.widget.TextView.checkForRelayout(TextView.java:8754)
	at android.widget.TextView.setText(TextView.java:5487)
	at android.widget.TextView.setText(TextView.java:5343)
	at android.widget.TextView.setText(TextView.java:5300)
	at com.hjq.toast.BaseToast.setText(BaseToast.java:32)
	at com.hjq.toast.ToastStrategy.handleMessage(ToastStrategy.java:86)
	at android.os.Handler.dispatchMessage(Handler.java:108)

**Comment by csh159** [comment]
没有在子线程，部分手机，很难复现，身边的几款手机没问题，但是上线就有的手机报这个错

**Comment by getActivity** [comment]
没有复现步骤，我是没有办法修复的
