### ISSUE TITLE
美图MP1603手机关了通知权限，无法Toast

### ISSUE THREAD

**Issue by RuanJH** [getActivity/ToastUtils#67]
引用的版本是8.8
美图手机MP1603,android版本7.1.1，本地调试关闭通知无法toast

**Comment by getActivity** [comment]
[toast-9.0.aar.zip](https://github.com/getActivity/ToastUtils/files/6302121/toast-9.0.aar.zip)

**Comment by getActivity** [comment]
小伙子，你测试一下用这个包看看可以不

**Comment by RuanJH** [comment]
美图这台手机可以正常toast了，是什么原因

**Comment by getActivity** [comment]
@RuanJH 这个应该是通知栏权限判断在这个手机上面不准导致的，不过框架设计在最新版本上面已经重构了，如果你的应用处于前台的情况下，会使用 WindowManager 来显示，如果你的应用处于后台的情况下，会使用原生的 Toast 来显示。

**Comment by getActivity** [comment]
@RuanJH 小伙子，你先用这个包，因为 jcenter 挂了，所以一时半会更新不上去，但是我会尽快更新。

**Comment by RuanJH** [comment]
那你这两天更新了通知我一下

**Comment by getActivity** [comment]
@RuanJH 小伙子，你可以 watch 本项目，这样就可以第一时间收到更新提醒。

**Comment by RuanJH** [comment]
9.0版本有bug的。
 E/CrashReport: java.lang.RuntimeException: This Toast was not created with Toast.makeText()
        at android.widget.Toast.setText(Toast.java:334)
        at com.hjq.toast.SystemToast.setText(SystemToast.java:33)
        at com.hjq.toast.ToastStrategy.handleMessage(ToastStrategy.java:128)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7804)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

**Comment by getActivity** [comment]
[toast-9.0.aar.zip](https://github.com/getActivity/ToastUtils/files/6315771/toast-9.0.aar.zip)

**Comment by getActivity** [comment]
小伙子，这个问题有人跟我反馈了，我已经修复好了，你用这个包再试试。

**Comment by RuanJH** [comment]
我还是先用8.8的吧，到时候你测试完稳定我再使用，怕出问题了

**Comment by RuanJH** [comment]
试了下还是一样有问题

**Comment by getActivity** [comment]
你现在是用 8.8 出现的问题呢还是用 9.0 出现的问题呢？

**Comment by RuanJH** [comment]
刚才你给的9.0的aar包

**Comment by getActivity** [comment]
```java
CrashReport: java.lang.RuntimeException: This Toast was not created with Toast.makeText()
at android.widget.Toast.setText(Toast.java:334)
at com.hjq.toast.SystemToast.setText(SystemToast.java:33)
at com.hjq.toast.ToastStrategy.handleMessage(ToastStrategy.java:128)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:227)
at android.app.ActivityThread.main(ActivityThread.java:7804)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
```
还是这个问题？

**Comment by getActivity** [comment]
如果是的话，请你回答以下问题：
1. 你这边是通过前台的方式显示 Toast 还是后台的方式 Toast？
2. 手机的品牌型号是什么？Android 版本是多少？
3. 项目的 targetSdkVersion 是多少？
4. 替换完 aar 包之后，有没有同步一下 Gradle ？

**Comment by RuanJH** [comment]
1.后台方式toast
2.所有机型
3.29
4.有同步和clean项目
java.lang.RuntimeException: This Toast was not created with Toast.makeText()
        at android.widget.Toast.setText(Toast.java:332)
        at com.hjq.toast.SystemToast.setText(SystemToast.java:37)
        at com.hjq.toast.ToastStrategy.handleMessage(ToastStrategy.java:126)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6335)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1097)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)

**Comment by getActivity** [comment]
[ToastUtils.apk.zip](https://github.com/getActivity/ToastUtils/files/6316836/ToastUtils.apk.zip)

**Comment by getActivity** [comment]
小伙子，我测试了一下，并没有出现你说的这个问题，你现在下载 Demo 测试一下有没有这个问题。

**Comment by RuanJH** [comment]
发消息去你的Gmail邮箱了。你查看下

**Comment by getActivity** [comment]
小伙子，框架最新代码已经发布，你可以更新一下版本试一下。

**Comment by getActivity** [comment]
@RuanJH 谷歌邮箱我暂时打不开，你有什么问题可以在这里说。

**Comment by RuanJH** [comment]
加我微信聊吧：335334696

**Comment by RuanJH** [comment]
9.0toast都引不进来了，是不是没有发布成功

**Comment by getActivity** [comment]
https://bintray.com/getactivity/maven/toast

**Comment by getActivity** [comment]
我看到 bintray 上面都发布成功了

**Comment by getActivity** [comment]
小伙子，别人跟我反馈也是说不行，要不你这边先用一下本地依赖。

**Comment by getActivity** [comment]
```groovy
maven { url 'https://dl.bintray.com/getactivity/maven/' }
```

**Comment by getActivity** [comment]
小伙子，我迁移到 JitPack 仓库了，麻烦你再更新一下远程依赖。

**Comment by getActivity** [comment]
小伙子，还有其他问题不，没有的话我就关闭 issue 了。

**Comment by RuanJH** [comment]
9.0版本，之前那个异常还是存在，就是在ActivityLifecycleCallbacks中的onActivityStopped弹toast。

**Comment by getActivity** [comment]
小伙子，麻烦你加一下我的 QQ 880634，我和你联调这个问题，Github 沟通效率低下。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/115326375-c15f3600-a1bf-11eb-8341-524aabf66172.png)
